### ISSUE TITLE
pdf download button

### ISSUE THREAD

**Issue by oksanasl** [oksinlove/oksinlove.github.io#3]
download button click should open a pdf file in a new tab 
[license.pdf](https://github.com/oksinlove/oksinlove.github.io/files/238692/license.pdf)

**Comment by LaryShadow** [comment]
how do u need to resolve this task:
 - on a click the file is going to download
 - on a click the print pop-up is appearing with pdf file assigned to it
?)

**Comment by oksanasl** [comment]
It should rather be the second variant if only these two are possible to
implement.

But actually neither the first nor the second option.

On a click a new tab with a pdf file should open.

Which one is better in your opinion?

2016-04-27 17:54 GMT+03:00 Valerii notifications@github.com:

**Comment by eralaz** [comment]
done!

**Comment by eralaz** [comment]
add more animation to those 2 buttons like background color chaging while move mouse over the button.

**Comment by eralaz** [comment]
4 sending call back sms via landing page u will need something like this
https://www.clickatell.com/pricing-and-coverage/message-pricing/
called sms api. 
While email can be send freely.

**Comment by eralaz** [comment]
implemented
